---
- hosts: localhost
  vars_files:
    - vars/undercloud_install.yaml
    - vars/undercloud_services.yaml
    - undercloud_config.yaml
  tasks:
    - name: Check Hardware
      import_tasks: tasks/check_prepared.yaml
      tags: always

    - name: Create stack user
      import_tasks: tasks/create_stack_user.yaml
      tags: uc_prepare

#    - name: Config host
#      import_tasks: tasks/setup_hostname.yaml

    - name: Install TripleO deps
      import_tasks: tasks/install_deps.yaml
      tags: uc_prepare

    - name: Deploy UnderCloud
      import_tasks: tasks/install_undercloud.yaml

    - name: Verify UnderCloud
      import_tasks: tasks/verify_undercloud.yaml
