---
- hosts: localhost
  tasks:
    - name: Check Hardware
      import_tasks: tasks/check_prepared.yaml

    - name: Create stack user
      import_tasks: tasks/create_stack_user.yaml

    - name: Install TripleO deps
      import_tasks: tasks/install_deps.yaml
