---
- hosts: localhost
  vars_files:
    - install_config.yaml
  tasks:
    - name: Check Hardware
      import_tasks: tasks/check_prepared.yaml
      tags: always

    - name: Create stack user
      import_tasks: tasks/create_stack_user.yaml
      tags: uc_prepare

    - name: Install TripleO deps
      import_tasks: tasks/install_deps.yaml
      tags: uc_prepare

    - name: Deploy UnderCloud
      import_tasks: tasks/install_undercloud.yaml
