---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Patch tripleo-client support local push
      patch:
        src: files/image_uploader.patch
        dest: /usr/lib/python2.7/site-packages/tripleo_common/image/image_uploader.py
      become: true
      become_user: root
      tags: always

    - block: 
        - name: Create folder to save images
          file:
            state: directory
            dest: "{{ oc_images_path }}"
  
        - name: Get overcloud image
          get_url:
            url:  "https://images.rdoproject.org/{{tripleo_release}}/rdo_trunk/current-tripleo/{{ item }}"
            dest: "/home/stack/oc_images/{{ item }}"
          with_items: "{{ oc_images }}"
  
        - name: Extract overcloud images
          unarchive:
            src: "{{ oc_images_path }}/{{ item }}"
            dest: "{{ oc_images_path }}"
          with_items: "{{ oc_images }}"
  
        - name: Upload overcloud images
          shell: |
            source ~/stackrc
            openstack overcloud image upload --image-path {{oc_images_path}}
      tags: 
       - prepare-oc-images
       - prepare_oc

    - block:
        - name: Create container-prepare-paremeter.yaml
          copy:
            src: container-prepare-parameter.yaml
            dest: /home/stack/container-prepare-paremeter.yaml

        - name: Create local container registry
          shell: |
            source ~/stackrc
            openstack tripleo container image upload --config-file /home/stack/container-prepare-paremeter.yaml
      tags: 
        - prepare-oc-container-images
        - prepare_oc

    - name: Create overcloud basic environments
