---
- name: Install undercloud
  hosts: localhost
  gather_facts: yes
  roles:
    - undercloud

- name: Prepare install Overcloud
  hosts: localhost
  gather_facts: no
  roles:
    - role: overcloud/validate
    - role: overcloud/prepare
