---
##############################
# Undercloud config (required)
##############################

# DNS nameserver(s) to use for the undercloud node. (list value)
undercloud_nameservers: 8.8.8.8,8.8.4.4

# List of ntp servers to use. (list value)
undercloud_ntp_servers: 172.20.0.22

# Network interface on the Undercloud that will be handling the PXE
# boots and DHCP for Overcloud instances. (string value)
local_interface: eth1

# MTU to use for the local_interface. (integer value)
local_mtu: 1500

# Makes ironic-inspector enroll any unknown node that PXE-boots
# introspection ramdisk in Ironic. By default, the "fake" driver is
# used for new nodes (it is automatically enabled when this option is
# set to True). Set discovery_default_driver to override.
# Introspection rules can also be used to specify driver information
# for newly enrolled nodes. (boolean value)
enable_node_discovery: true

# Enable Undercloud debug
undercloud_debug: true

# Whether to update packages during the Undercloud install. (boolean
# value)
undercloud_update_packages: false

# Whether to install Tempest in the Undercloud. (boolean value)
enable_tempest: false

# Whether to install Telemetry services (ceilometer, gnocchi, aodh,
# panko ) in the Undercloud. (boolean value)
enable_telemetry: false

# Whether to install the TripleO UI. (boolean value)
enable_ui: false

# List of enabled bare metal drivers. (list value)
enabled_drivers: pxe_ipmitool,pxe_ilo

# Keystone admin password. If left unset, one will be automatically
# generated. (string value)
undercloud_admin_password: password

#############################
# Undercloud config (options)
#############################

# Network CIDR for the Neutron-managed network for Overcloud
# instances. This should be the subnet used for PXE booting. (string
# value)
network_cidr: 192.168.24.0/24

# Network that will be masqueraded for external access, if required.
# This should be the subnet used for PXE booting. (string value)
masquerade_network: 192.168.24.0/24

# IP information for the interface on the Undercloud that will be
# handling the PXE boots and DHCP for Overcloud instances.  The IP
# portion of the value will be assigned to the network interface
# defined by local_interface, with the netmask defined by the prefix
# portion of the value. (string value)
local_ip: 192.168.24.1/24

# Network gateway for the Neutron-managed network for Overcloud
# instances. This should match the local_ip above when using
# masquerading. (string value)
network_gateway: 192.168.24.1

# Start of DHCP allocation range for PXE and DHCP of Overcloud
# instances. (string value)
dhcp_start: 192.168.24.5

# End of DHCP allocation range for PXE and DHCP of Overcloud
# instances. (string value)
dhcp_end: 192.168.24.25

#Inspection ip range use the same cidr with deploy format
inspection_iprange: 192.168.24.100,192.168.24.120

###################################
# Undercloud host config (required)
###################################
# Offline
offline_install: false

# Undercloud will install ceph-ansible for use external ceph
# (boolean)
external_ceph: false

# TripleO version
tripleo_version: stein

# Undercloud need config hostname to deploy
# The /etc/hosts result: >
# 127.0.0.1 undercloud undercloud.inwinstack.com
# Undercloud fqdn to config /etc/hosts and hostnamectl
undercloud_fqdn: undercloud.inwinstak.com
# Undercloud hostname to config /etc/hosts
undercloud_hostname: undercloud

#############################################
# Undercloud install extra packages (options)
#############################################

# Install extra packages (list value)
# eg. extra_pkgs: [vim, iperf3, sl]
extra_pkgs: []
