---
- name: Generate undercloud.conf
  merge_configs:
    sources:
      - "{{ playbook_path_output.stdout }}/templates/undercloud.conf.default"
      - "{{ playbook_path_output.stdout }}/override_undercloud.conf"
    dest: /home/stack/undercloud.conf
    owner: stack
    group: stack
    mode: 0644
  tags: create-config
