---
- name: Update System
  yum:
    name: '*'
    state: latest
  tags: yum_update

- name: Try to find tripleo repo
  find:
    paths: /tmp
    patterns: '^python2-tripleo-repos-\w*.*\d*.centos.noarch.rpm$'
    use_regex: yes
  register: find_repo
  when: offline_install == false

- name: Try download TripleO repo from internet
  script: >
    tools/get_tripleo_repo
  when: offline_install == false

- name: Find download tripleo repo
  find:
    paths: /tmp
    patterns: '^python2-tripleo-repos-\w*.*\d*.centos.noarch.rpm$'
    use_regex: yes
  register: find_repo
  when: offline_install == false

- name: TripleO repo is "{{ find_repo.files[0].path | basename }}"
  set_fact:
    repo_name: "{{ find_repo.files[0].path | basename }}"
  when: offline_install == false

- name: Try copy rpm from local to remote server
  copy:
    src: "/tmp/{{ repo_name }}"
    dest: "/tmp/{{ repo_name }}"
  when: offline_install == false

- name: Install TripleO repo
  yum:
    name: "/tmp/{{ python_tripleo_repo }}"
  when: offline_install == false

- name: Enable TripleO repo
  shell: tripleo-repos -b "{{ tripleo_version }}" current ceph
  become: true
  when: offline_install == false
  tags: tripleo-rpm

- name: Install pkgs
  yum:
    name:
      - python-tripleoclient
      - vim
      - tmux
  tags: install-pkgs
