---
- name: Create undercloud.conf
  file:
    path: /home/stack/undercloud.conf
    state: touch

- name: Insert options to undercloud.conf
  shell: |
    crudini --merge /home/stack/undercloud.conf < templates/undercloud.conf.origin
    crudini --merge /home/stack/undercloud.conf < undercloud.conf
  tags: create_config

- name : Install undercloud
  shell: >
    openstack undercloud install
  become: true
  become_user: stack
  tags: install-undercloud


