---
- hosts: localhost
  vars_files:
    - ../vars/undercloud_config.yaml
  tasks:
    - name: Create undercloud.conf
      template: 
        src: ../templates/undercloud.conf.j2
        dest: /home/stack/undercloud.conf
        owner: stack
        group: stack
        mode: 0644
    
    - name : Install undercloud
      script: ../script/undercloud_install.sh
      become: true
      become_user: stack
