---
- name: Check TripleO repo installed or not
  yum:
    list=python2-tripleo-repos
  register: pkg

- name: Install TripleO repo
  script: >
    ../tools/get_tripleo_repo
  when: offline_install == false and pkg.results|selectattr("yumstate", "match", "installed")|list|length == 0

- name: Enable TripleO repo "{{ tripleo_version }}"
  shell: tripleo-repos -b "{{ tripleo_version }}" current ceph
  become: true
  when: offline_install == false

- name: Install tripleo client
  yum:
    name:
      - python-tripleoclient

- name: Copy sample config for stack user
  copy:
    src: /usr/share/python-tripleoclient/undercloud.conf.sample
    dest: /usr/home/stack/undercloud.conf.sample
    group: stack
    owner: stack
