---
- name: Create undercloud.conf
  copy:
    src: undercloud.conf
    dest: /home/stack/undercloud.conf
    owner: stack
    group: stack
  tags: uc_prepare

- name : Install undercloud
  shell: >
    openstack undercloud install
  no_log: true
  become: true
  become_user: stack
  tags: install-undercloud


