ControllerSchedulerHints: 'controller'
ComputeSchedulerHints: 'compute'
ControllerHostnameMap:
    - controller0
    - controller1
    - controller2
ComputeHostNameMap:
    - com1
    - com2
# The DNS domain used for the hosts. This must match the overcloud_domain_name configured on the undercloud.
# Type: string
CloudDomain: ops.local

# The DNS name of this cloud. E.g. ci-overcloud.tripleo.org
# Type: string
CloudName: overcloud.ops.local

# The DNS name of this cloud's provisioning network endpoint. E.g. 'ci-overcloud.ctlplane.tripleo.org'.
# Type: string
CloudNameCtlplane: overcloud.ctlplane.ops.local

# The DNS name of this cloud's internal API endpoint. E.g. 'ci-overcloud.internalapi.tripleo.org'.
# Type: string
CloudNameInternal: overcloud.internalapi.ops.local

# The DNS name of this cloud's storage endpoint. E.g. 'ci-overcloud.storage.tripleo.org'.
# Type: string
CloudNameStorage: overcloud.storage.ops.local

# The DNS name of this cloud's storage management endpoint. E.g. 'ci-overcloud.storagemgmt.tripleo.org'.
# Type: string
CloudNameStorageManagement: overcloud.storagemgmt.ops.local
